;; -*- lexical-binding: t; -*-

(TeX-add-style-hook
 "master"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("amsmath" "") ("amssymb" "") ("amsthm" "") ("stmaryrd" "") ("xy" "all") ("verbatim" "") ("fullpage" "") ("hyperref" "") ("setspace" "") ("graphicx" "") ("xcolor" "dvipsnames") ("tikz-cd" "") ("mathtools" "") ("multicol" "") ("enumitem" "shortlabels" "") ("inputenc" "utf8") ("fontenc" "T1") ("lmodern" "") ("geometry" "margin=1in") ("microtype" "") ("fancyhdr" "")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "amsmath"
    "amssymb"
    "amsthm"
    "stmaryrd"
    "xy"
    "verbatim"
    "fullpage"
    "hyperref"
    "setspace"
    "graphicx"
    "enumitem"
    "xcolor"
    "tikz-cd"
    "mathtools"
    "multicol"
    "inputenc"
    "fontenc"
    "lmodern"
    "geometry"
    "microtype"
    "fancyhdr")
   (TeX-add-symbols
    '("interior" 1)
    '("norm" 1)
    '("abs" 1)
    "bA"
    "bB"
    "bC"
    "bD"
    "bE"
    "bF"
    "bG"
    "bH"
    "bI"
    "bJ"
    "bK"
    "bL"
    "bM"
    "bN"
    "bO"
    "bP"
    "bQ"
    "bR"
    "bS"
    "bT"
    "bU"
    "bV"
    "bW"
    "bX"
    "bY"
    "bZ"
    "bbA"
    "bbB"
    "bbC"
    "bbD"
    "bbE"
    "bbF"
    "bbG"
    "bbH"
    "bbI"
    "bbJ"
    "bbK"
    "bbL"
    "bbM"
    "bbN"
    "bbO"
    "bbP"
    "bbQ"
    "bbR"
    "bbS"
    "bbT"
    "bbU"
    "bbV"
    "bbW"
    "bbX"
    "bbY"
    "bbZ"
    "sA"
    "sB"
    "sC"
    "sD"
    "sE"
    "sF"
    "sG"
    "sH"
    "sI"
    "sJ"
    "sK"
    "sL"
    "sM"
    "sN"
    "sO"
    "sP"
    "sQ"
    "sR"
    "sS"
    "sT"
    "sU"
    "sV"
    "sW"
    "sX"
    "sY"
    "sZ"
    "cG"
    "BB"
    "CC"
    "simto"
    "epi"
    "mon"
    "from"
    "id"
    "ev"
    "im"
    "push"
    "FF"
    "ZZ"
    "Fun"
    "Maps"
    "Mat"
    "LP"
    "coker"
    "spec"
    "ext"
    "x"
    "ar"
    "arr"
    "diam"
    "eps")
   (LaTeX-add-environments
    '("exercise" 1)
    "solution")
   (LaTeX-add-amsthm-newtheorems
    "theorem"
    "proposition"
    "lemma"
    "corollary"
    "definition"
    "nondefinition"
    "remark"
    "example"
    "innercustomthm"))
 :latex)

